INSERT INTO shoes (name, brand, colorway, silhouette, release_year, release_date, retail_price, market_price, description, image_url, current_bid, lowest_ask, total_sales)
VALUES (
    'Air Jordan 13 Retro ''Black University Blue''',
    'Jordan',
    'Black/University Blue/White',
    'Air Jordan 13',
    '2022',
    '2022-12-29',
    200,
    200,
    'The Air Jordan 13 Retro ''Black University Blue'' dresses the championship silhouette in a familiar two-tone color scheme. The upper pairs reflective black mesh overlays with matching black leather construction throughout the forefoot. Synthetic suede in a contrasting Carolina blue finish wraps around the heel and collar, accented with a holographic cat eye on the lateral side. The soft material extends to a midsole enhanced with a carbon fiber plate and Zoom Air cushioning. Underfoot, the panther paw outsole features herringbone traction pods for superior grip.',
    'https://sneakernews.com/wp-content/uploads/2022/03/air-jordan-13-university-blue-black-2022-release-date.jpg',
    250,
    300,
    0
), (
    'Wmns Air Jordan 1 Retro High OG ''Twist 2.0''',
    'Jordan',
    'Medium Grey/Black/White',
    'Air Jordan 1',
    '2022',
    '2022-12-22',
    250,
    250,
    'The women''s Air Jordan 1 Retro High OG ''Twist 2.0'' presents the sequel to the AJ1 ''Twist'' from 2019, featuring the same unique build but with a subtly refreshed palette. Like the older shoe, the upper pairs black pony hair with a smooth leather underlay. The latter is updated in a light grey hue, replacing the crisp white finish of the original. A molded Wings logo in metallic silver shines on the lateral collar, adding a bit of polish to the neutral design.',
    'https://cdn.shopify.com/s/files/1/0086/5284/9248/products/ST045_250x.jpg?v=1604545223',
    320,
    350,
    0
), (
    'Travis Scott x Air Jordan 1 Low OG SP ''Black Phantom''',
    'Jordan',
    'Black/Phantom',
    'Air Jordan 1',
    '2022',
    '2022-12-15',
    300,
    300,
    'The Travis Scott x Air Jordan 1 Low OG SP ''Black Phantom'' reunites Jordan Brand with the chart-topping rapper who put his own indelible stamp on the sneaker that started it all. Featuring similar color blocking and materials used on Scott''s ''Mocha'' Air Jordan 1 Low from 2019, the low-top carries a black nubuck upper with charcoal suede overlays at the forefoot and heel. The lateral side is marked with an oversized rear-facing Swoosh in off-white leather, while the heel tabs are branded with mismatched Catcus Jack and Jordan Wings logos. Anchoring the sneaker is a traditional rubber cupsole that pairs aged sidewalls with a black rubber outsole.',
    'https://sneakerbardetroit.com/wp-content/uploads/2022/07/Travis-Scott-Air-Jordan-1-Low-Black-Phantom-DM7866-001-Release-Date-2022.jpeg',
    300,
    300,
    0
), (
    'Nike Air Force 1 Low Multi-Swoosh White Particle Grey Photon Dust Bright Crimson (GS)',
    'Nike',
    'White/Particle Grey/Photon Dust/Bright Crimson',
    'Air Force 1',
    '2022',
    '2022-12-15',
    95,
    78,
    'The legend lives on in the Nike Air Force 1, which stays true to its roots with iconic AF-1 style and Nike Air for all-day comfort and long-lasting wear.',
    'https://cdn.flightclub.com/750/TEMPLATE/293419/1.jpg',
    118,
    110,
    0
), (
    'Air Jordan 11 Retro ''Cherry''',
    'Jordan',
    'White/Varsity Red/Black',
    'Air Jordan 11',
    '2022',
    '2022-12-10',
    225,
    556,
    'The Air Jordan 11 Retro ''Cherry'' showcases familiar two-tone color blocking that recalls the low-top AJ11 ''Varsity Red'' from 2001. The upper is crafted from white ballistic mesh with tonal webbing eyelets and a shiny patent leather mudguard in a bold scarlet hue. Matching red accents land on the interior collar and an embroidered Jumpman on the white leather heel overlay. Lightweight cushioning arrives via a plush Phylon midsole, supported underfoot by a carbon fiber spring plate and a translucent rubber outsole.',
    'https://cdn.flightclub.com/TEMPLATE/011574/1.jpg',
    600,
    620,
    0
), (
    'Air Jordan 7 Retro ''Cardinal'' 2022',
    'Jordan',
    'White/Black/Cardinal Red/Chutney',
    'Air Jordan 7',
    '2022',
    '2022-11-26',
    220,
    220,
    'The 2022 reissue of the Air Jordan 7 Retro ''Cardinal'' revives an OG colorway of the silhouette that Michael Jordan wore when he clinched his second NBA championship. The sneaker sports a white leather upper with perforated detailing and a Huarache-like interior sleeve for a snug fit. Branding elements include a ''23'' heel patch, an embroidered Jumpman on the lateral ankle, and ''Air Jordan'' lettering on the tongue. Enhanced with hidden Air-sole cushioning, the navy-colored Phylon midsole features angular Cardinal red accents that give the shoe its name.',
    'https://cdn.flightclub.com/750/TEMPLATE/010309/1.jpg',
    210,
    230,
    0
), (
    'Air Jordan 1 Retro High OG ''Gorge Green''',
    'Jordan',
    'Gorge Green/White/Metallic Silver',
    'Air Jordan 1',
    '2022',
    '2022-11-12',
    180,
    180,
    'The Air Jordan 1 Retro High OG ''Gorge Green'' features color blocking reminiscent of the iconic Air Jordan 1 CO.JP ''Midnight Navy,'' originally released in 2001 and reissued in 2020. The high-top carries a tumbled leather upper that pairs a white base with forest green overlays at the forefoot and heel. Branding elements include a metallic silver Swoosh and a jeweled Wings logo on the lateral collar flap. Underpinning the sneaker is a rubber cupsole, highlighted by encapsulated Air-sole cushioning and a green rubber outsole.',
    'https://cdn.shopify.com/s/files/1/0795/6433/products/gorgegreen.png?v=1649093528',
    358,
    370,
    0
), (
    'Nike SB Dunk Low Philadelphia Phillies',
    'Nike',
    'Valor Blue/Team Maroon/White/Gum',
    'Dunk',
    '2022',
    '2022-07-26',
    115,
    158,
    'While the retro silhouette is rooted in basketball, the Nike Dunk Low Premium SB ''Philadelphia Phillies'' shifts the focus to the baseball diamond, featuring a distinctive color palette that pays homage to the historic MLB franchise. The suede upper is finished in Valor Blue, contrasted by a Team Maroon Swoosh outlined in white trim. A Nike SB tag decorates the stuffed tongue, while mismatched interior tags display a cheesesteak graphic on the left shoe and a Liberty Bell graphic on the right. Underfoot, a gum rubber outsole provides grippy traction.',
    'https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcR2vyXAI7oSMhH2ur2W2lxZDKmWVZBG7nbhS_iPy6PZC-KssTOI_VsMzKVcadw-efk3p67xxP-bqymqokJLPDa0OZJ8wU8FFA',
    345,
    360,
    4532
), (
    'Bad Bunny x Forum Buckle Low ''Blue Tint''',
    'Adidas',
    'Blue Tint/Light Blue/Clear Blue',
    'Forum',
    '2022',
    '2022-08-27',
    160,
    685,
    'Just as the previous pairs, Bad Bunny offers a tonal adidas Forum Buckle Low with various shades of blue. The upper is made entirely out of suede, with the exception of the mudguard that runs around the rear. Sky blue fills the toebox and quarters, while baby blue dresses the remaining overlays. A deeper shade of blue appears on the signature adidas Three-Stripes and heel counter. A two-tone midsole completes the sneaker.',
    'https://cdn.flightclub.com/750/TEMPLATE/314012/1.jpg',
    1100,
    1500,
    0
), (
    'Yeezy Boost 700 ''Hi-Res Blue''',
    'Adidas',
    'Hi-Res Blue/Hi-Res Blue/Hi-Res Blue',
    'Yeezy Boost 700',
    '2022',
    '2022-08-02',
    260,
    940,
    'The adidas Yeezy Boost 700 ''Hi-Res Blue'' delivers an energetic colorway of Kanye West''s bulky lifestyle runner. Vibrant blue and purple hues are executed on the upper, composed of airy mesh with tonal leather and suede overlays and a contrasting black suede mudguard. Responsive cushioning is provided by a full-length Boost midsole, hidden inside a blue TPU carrier with sculpted sidewalls and bold bursts of crimson along the forefoot. A herringbone-traction rubber outsole offers grippy traction underfoot.',
    'https://cdn.flightclub.com/TEMPLATE/320358/1.jpg',
    1230,
    1500,
    304
), (
    'Yeezy Boost 350 ''Turtle Dove'' 2022',
    'Adidas',
    'Turtle Dove/Blue Gray/Core White',
    'Yeezy Boost 350',
    '2022',
    '2022-08-01',
    60,
    1000,
    'The 2022 edition of the adidas Yeezy Boost 350 ''Turtle Dove'' brings back the first ever 350 colorway. True to the original 2015 release, the minimalist silhouette carries a patterned Primeknit upper in off-white and dark grey. A black suede overlay reinforces the medial quarter panel, while a textile pull tab marked with red stitching provides easy on and off. The sneaker is mounted on a full-length Boost midsole, fully enveloped in an ivory TPU cage for added durability and support.',
    'https://cdn.flightclub.com/TEMPLATE/201114/1.jpg',
    1230,
    1500,
    238
), (
    'Dunk Low Retro Premium ''Graffiti''',
    'Nike',
    'Black/Summit White/Red Orbit/Black',
    'Dunk',
    '2022',
    '2022-07-28',
    110,
    117,
    'The Nike Dunk Low Retro Premium ''Graffiti'' features a canvas build with frayed edges and a mixed blend of pink, purple, grey, and black, rendered in a unique arrangement that makes no two shoes alike. Graffiti-style Nike branding adorns the shoe''s custom sockliners, while a reflective Swoosh adds a hi-vis element to the street-ready design. A contrasting white finish is applied to the rubber midsole, accented with contrast black stitching and supported by a black rubber outsole.',
    'https://cdn.shopify.com/s/files/1/0099/5232/9785/products/DM0108-001_800x.jpg?v=1654071208',
    150,
    200,
    874
), (
    'Nike Air Max Sunder SP Comme des Garcons Homme Plus White Black',
    'Nike',
    'White/Black/White',
    'Air Sunder Max',
    '2022',
    '2022-07-21',
    350,
    392,
    'The Comme des Garçons Homme Plus x Nike Air Sunder Max ''White Black'' revives a vintage trainer originally released in 1999. Debuting in July 2021 during CDG Homme Plus'' Spring/Summer 2022 runway show in Tokyo, the sleek silhouette features a white neoprene upper with a zippered shroud that conceals the lace bed. A black nubuck mudguard offers enhanced durability, while dual pull tabs provide easy on and off. Lightweight cushioning arrives via a Phylon midsole with visible Air-sole units in the forefoot and heel.',
    'https://cdn.snkrdunk.com/uploads/media/20220421092150-1.jpeg',
    450,
    490,
    475
), (
    'Air Jordan 6 Retro ''Georgetown''',
    'Jordan',
    'Magnet/College Navy',
    'Air Jordan 6',
    '2022',
    '2022-09-03',
    200,
    550,
    'The Air Jordan 6 Retro ''Georgetown'' showcases the signature colors of the Hoyas, the team that lost to Michael Jordan''s North Carolina Tar Heels in the 1982 NCAA championship game. The legacy silhouette makes use of a grey suede upper with perforated detailing and a Huarache-like inner sleeve. Contrasting navy accents make their way to the heel tab, lace locks, and Jumpman branding hits embroidered on the tongue and back heel. The sneaker rests on a two-tone polyurethane midsole, featuring a visible Air-sole unit in the heel and a translucent rubber outsole underfoot.',
    'https://www.nicekicks.com/files/2022/07/Air-Jordan-6-Georgetown-CT8529-012-02-750x750.jpg',
    679,
    780,
    0
), (
    'adidas Karlie Kloss Trainer XX92 Wonder Mauve',
    'Adidas',
    'Wonder Mauve/Wonder Mauve/Core Black',
    'Trainer XX92',
    '2022',
    '2022-08-31',
    90,
    90,
    'The Karlie Kloss x adidas women''s Trainer XX92 Vegan ''Wonder Mauve'' is taken from a capsule collection with the model, entrepreneur, and activist. Equipped with a stretchy sock-like cuff, the pink cotton canvas upper is made in part with recycled polyester. Dual adidas and Karlie Koss branding decorates the tongue tag. A contrasting black toe cap is matched by the elevated platform midsole, bringing a fashion-forward element to the traditional canvas sneaker.',
    'https://staticg.sportskeeda.com/editor/2022/07/d39d0-16573006824965-1920.jpg',
    90,
    100,
    0
), (
    'Jordan 1 Retro High OG Stealth',
    'Jordan',
    'Stealth/White',
    'Air Jordan 1',
    '2022',
    '2022-08-27',
    170,
    450,
    'The Air Jordan 1 Retro High OG ''Stealth'' applies an understated two-tone finish to the sneaker that started it all. The all-leather build pairs a stark white base with neutral grey accents on the perforated toe box, signature Swoosh, and heel and collar overlay. The latter is branded with a retro Wings logo, while a woven Nike Air tag graces the breathable nylon tongue. The high-top rests on a rubber cupsole with an encapsulated Air-sole unit in the heel for lightweight cushioning.',
    'https://www.kickbulk.co/image/catalog/JORDAN-1/555088-037/Air-Jordan-1-High-OG-Stealth-555088-037-1.jpg',
    500,
    550,
    673
), (
    'Jordan 3 Retro Dark Iris',
    'Jordan',
    'White/Black/Dark Iris/Cement Grey',
    'Air Jordan 3',
    '2022',
    '2022-08-24',
    200,
    180,
    'The Air Jordan 3 Retro ''Dark Iris'' brings a revitalized color palette to the hardwood classic that introduced visible Air cushioning to the Jordan franchise. The sneaker utilizes a white tumbled leather upper with signature elephant print overlays in a dark grey finish. Violet accents make their way to the eyelets, perforated collar and the rear of the polyurethane midsole. Jumpman branding hits adorn the leather tongue and molded heel overlay. Underfoot, a grey rubber outsole provides durable traction.',
    'https://media.sivasdescalzo.com/media/catalog/product/D/M/DM0967-105_sivasdescalzo-Jordan-AIR_JORDAN_3_RETRO_GS_-1654770931-1.jpg?quality=70&auto=webp&fit=bounds&width=420',
    230,
    260,
    0
), (
    'Jordan 13 Retro French Blue',
    'Jordan',
    'White/Fire Red-French Blue-Light Steel Grey',
    'Air Jordan 13',
    '2022',
    '2022-08-20',
    200,
    324,
    'The Air Jordan 13 Retro ''French Blue'' showcases cool tones on a classic silhouette that takes inspiration from Michael Jordan''s ''Black Cat'' persona. The upper combines white dimpled leather overlays with a grey leather forefoot and blue synthetic suede paneling along the midfoot and heel. The signature holographic eye adorns the lateral collar, while a crimson Jumpman on the tongue provides an unexpected pop of contrasting color. Underfoot, the panther paw outsole features herringbone-traction rubber pods and a carbon fiber shank plate for midfoot stability.',
    'https://www.nicekicks.com/files/2022/07/Air-Jordan-13-French-Blue-414571-164-02-750x750.jpg',
    356,
    400,
    0
), (
    'Jordan 14 Retro Ginger (2022)',
    'Jordan',
    'Light Ginger/Black/White',
    'Air Jordan 14',
    '2022',
    '2022-08-17',
    210,
    382,
    'The Air Jordan 14 Retro ''Ginger'' delivers a twist on the OG Air Jordan 14 Low ''Ginger'' from 1999. Updated in mid-top form, the upper carries a golden tan nubuck upper with a white leather forefoot overlay. Jumpman logos appear on a Ferrari-inspired badge and rubberized heel overlay, featuring a debossed tire-tread texture and oversized ''23'' branding. Encapsulated Zoom Air cushioning enhances the Phylon midsole, accented with angular teeth-like detailing and supported by a TPU shank plate.',
    'https://www.nicekicks.com/files/2022/07/Air-Jordan-14-Ginger-487471-701-01-750x750.jpg',
    487,
    560,
    0
), (
    'Jordan 7 Retro Citrus (2022) (PS)',
    'Jordan',
    'Black/Citrus-Varsity Red',
    'Air Jordan 7',
    '2022',
    '2022-08-13',
    110,
    120,
    'The 2022 edition of the Air Jordan 7 Retro PS ''Citrus'' brings back an energetic colorway from 2006. Returning in time to celebrate the title-winning shoe''s 30th anniversary, the classic silhouette features a black nubuck upper with perforated detailing contrast yellow stitching throughout. A Jumpman logo graces the lateral collar in matching yellow embroidery, while a crimson ''23'' adorns the molded heel patch. The sneaker rides on a black polyurethane midsole with angular accents in Citrus and Varsity Red.',
    'https://img.bstn.com/eyJidWNrZXQiOiJic3RuLWltYWdlLXNlcnZlciIsImtleSI6ImNhdGFsb2cvcHJvZHVjdC9DVTkzMDctMDgxL0NVOTMwNy0wODEtMDMuanBnIiwiZWRpdHMiOnsicmVzaXplIjp7ImZpdCI6ImNvbnRhaW4iLCJ3aWR0aCI6NTgwLCJoZWlnaHQiOjcyNSwiYmFja2dyb3VuZCI6eyJyIjoyNTUsImciOjI1NSwiYiI6MjU1LCJhbHBoYSI6MX19fX0=',
    168,
    210,
    0
), (
    'Air Jordan 5 Retro GS ''Concord''',
    'Jordan',
    'White/Dark Concord/Black',
    'Air Jordan 5',
    '2022',
    '2022-08-13',
    180,
    205,
    'Made for big kids, the Air Jordan 5 Retro GS ''Concord'' brings a familiar accent color to the legacy silhouette. The upper is crafted from white leather with molded eyelets, translucent quarter panel netting, and a silver reflective tongue. The latter is marked with a purple embroidered Jumpman, matching the sneaker''s signature lace locks and textile lining. A second Jumpman icon decorates the heel overlay. Anchoring the mid-top is a black polyurethane midsole, featuring purple shark tooth detailing and a visible Air-sole unit in the heel.',
    'https://www.nicekicks.com/files/2022/07/Air-Jordan-5-Concord-DD0587-141-010-750x750.jpg',
    270,
    295,
    0
), (
    'Nike Air Force 1 Mid Off-White Pine Green',
    'Nike',
    'Pine Green/White-White',
    'Air Force 1',
    '2022',
    '2022-08-01',
    150,
    600,
    'Recently, a green-colored Air Force 1 Mid appeared with typical Off-White details: zip-ties, contrasting tabs at the profile swooshes and “deconstructed” builds. The upcoming pair resembles the ultra-exclusive low-top Air Force 1 pairs that Abloh prepped for both the Brooklyn Museum and Louis Vuitton before passing. Although the latest Off-White Nikes feature some of Abloh''s signature touches, they also don a previously-unseen logo of a candle holder at the lateral heel, an “OFF” in Virgil''s handwriting on the right heel, and a graffiti-style “AIR” at the tongue. The shoes'' morphed sole unit exposes a Air Max unit, building on the thought process behind the original “The Ten” collection that debuted in 2017.',
    'https://luckydraw-media.s3.amazonaws.com/product/1939/main_carousel/21125.jpg',
    705,
    770,
    0
), (
    'Yeezy 450 ''Utility Black''',
    'Adidas',
    'Utility Black/Utility Black/Utility Black',
    'Yeezy 450',
    '2022',
    '2022-08-01',
    210,
    1036,
    'The adidas Yeezy 450 ''Utility Black'' tempers its unconventional design language with a stealthy one-note finish. The lightweight build utilizes a one-piece black knit upper, secured with lace closure and a stretchy, sock-like cuff. A color-matched PU-injected midsole wraps up the sides and heel, delivering a supportive fit with a one-of-a-kind aesthetic. Underfoot, the contoured outsole features grooved lines for superior traction.',
    'https://www.soleretriever.com/_next/image?url=https%3A%2F%2Fmedia.soleretriever.com%2F5db59e5b-1a3b-4315-b3e8-d57f1b440aef.png&w=1200&q=75',
    2030,
    2340,
    0
), (
    'adidas Rivalry Promodel Sankuanz',
    'Adidas',
    'Footwear White/Silver Metallic/Core Black',
    'Rivalry',
    '2020',
    '2020-10-10',
    50,
    59,
    'The adidas x Sankuanz Rivalry Promodel are part of the sneakers pack of the new collaboration between adidas and Sankuanz. It is a hybrid silhouette that is based on the design of the shoes from the period between the 60s until the 90s. This model reinvents the 1969 Promodel combining elements of the classic Rivalry of the 80s courts.',
    'https://footdistrict.com/media/resize/840x1050/catalog/product/p/r/producto_02_10_208_1/adidas-x-sankuanz-rivalry-promodel-fy3501-0.jpg',
    65,
    69,
    3496
), (
    'adidas Yung-1 420',
    'Adidas',
    'Grey Two/Raw Grey/Shock Yellow',
    'Yung-1',
    '2019',
    '2019-04-20',
    120,
    74,
    'Bringing back 90s nostalgia, adidas dropped the Yung-1 &#39;420&#39; in April 2019, just in time for the holiday. The easy-going sports shoe is a reincarnation of the retro Falcon Dorf release in 1997. Highlighting a combination of canvas, nubuck leather and suede, the retro upper keeps feet supported and cozy. Building on the laid-back vibe, the light blue tie-dyed colorway is accented by the iconic three stripes on the midfoot with a bright yellow hit to brighten up the otherwise subdued palette.',
    'https://cdn.shopify.com/s/files/1/0603/3031/1875/products/main-square_a6dc131b-1250-4e5c-8eca-6fc3b3f7fcf7.jpg?v=1656281920',
    75,
    80,
    6732
), (
    'adidas Superstar Active Red',
    'Adidas',
    'Cloud White/Active Red/Cloud White',
    'Superstar',
    '2019',
    '2019-07-01',
    100,
    77,
    'The adidas Superstar, designed by Horst Dassler, first debuted in 1969 as an all-leather basketball sneaker. This &#39;Active Red&#39; edition was released in July 2019 and stays true to the classic. It features light touches to the overall design, including the addition of a brilliant red hue on the heel, tongue branding and Three-Stripes. &#39;Superstar&#39; lettering arrives on the sidewall, debossed for a subtle effect. A hallmark of the Superstar, a rubber shell toe is included for durability.',
    'https://assets.adidas.com/images/w_320,f_auto,q_auto,fl_lossy,c_fill,g_auto/a0f832b935524a2bad4bada8003f0bdf_9366/Superstar_Shoes_White_GZ3741_01_standard.jpg',
    90,
    95,
    4522
), (
    'adidas Continental Aero Blue',
    'Adidas',
    'Aero Blue/Scarlet/Collegiate Navy',
    'Continental 80',
    '2018',
    '2018-08-30',
    80,
    49,
    'The Continental 80 is a new but familiar design that incorporates elements that reference indoor court shoes of the 80s and the original adidas Continental silhouette. The shoe is constructed with a soft tumbled leather that sports an Aero Blue swatch throughout the majority of the makeup, while red and navy accents line the side panels. Complete with vintage adidas and trefoil logos, the shoe also rests on a vintage court midsole.',
    'https://assets.adidas.com/images/w_600,f_auto,q_auto/7d8553a15bd64257a25ba97b012ed5d2_9366/Continental_80_Shoes_White_G27706_07_standard.jpg',
    70,
    80,
    5285
), (
    'adidas Futurecraft 4D Carbon',
    'Adidas',
    'Core Black/Carbon/Core Black',
    'Futurecraft 4D',
    '2021',
    '2021-01-01',
    250,
    286,
    'The adidas Futurecraft 4D ''Black Carbon'' treats the groundbreaking running shoe to a stealthy monochromatic makeover. The upper is crafted from black Primeknit that hugs the foot in seamless, distraction-free support. Charcoal grey three-stripes adorns the quarter panel, while the tongue tag displays a discreet adidas logo in white. Precision-tuned cushioning arrives via adidas'' 4D midsole, featuring a lattice structure based on 17 years of running data. Underfoot, a Continental rubber outsole provides grippy traction in wet or dry conditions.',
    'https://i.ebayimg.com/images/g/s-sAAOSwSENhoVCL/s-l500.jpg',
    286,
    298,
    3210
), (
    'adidas NMD Racer Alphatype',
    'Adidas',
    'Core Black/Core Black/Flash Red',
    'NMD Runner',
    '2018',
    '2018-11-22',
    180,
    82,
    'The NMD_Racer ''Alphatype'' is drawn from a November 2018 collection that brought together adidas'' key releases from 2018. This special-edition shoe carries an all-black color scheme, rendered on a minimalist Primeknit upper that''s accented with a contrasting pink tongue tag and an adidas Alphatype logo on the lateral heel. The design is finished with a Boost midsole and a gum rubber outsole with a Quickstrike insert.',
    'https://cdna.lystit.com/photos/allikestore/a6ffede9/adidas-Black-Nmd-Racer-Pk-Alphatype.jpeg',
    99,
    109,
    2452
), (
    'adidas 4D Fusio Sunset',
    'Adidas',
    'Chalk White/Core Black/Light Purple',
    '4D Fusio',
    '2021',
    '2021-02-04',
    200,
    75,
    'The adidas 4D Fusio ''Sunset'' combines a vibrant palette with the brand''s groundbreaking 3D-printed tooling. Contrasting off-white and orange fibers make up the composition of the Primeknit textile upper, secured with an integrated lacing system that incorporates a series of translucent tubes affixed to the sneaker''s side panels. Finely tuned cushioning comes courtesy of the lattice-like 4D midsole, finished in purple and partially wrapped in an orange and pink TPU belt that extends from the toe and around the heel.',
    'https://assets.solesense.com/en/images/products/500/adidas-4d-fusio-sunset-fz3894_1.jpg',
    99,
    102,
    3116
), (
    'adidas Basket Profi Black',
    'Adidas',
    'Black / Core Black / Gold Metallic',
    'Basket Profi',
    '2020',
    '2020-01-01',
    100,
    117,
    'Based on a vintage basketball shoe originally released in 1969, the adidas Basket Profi ''Core Black'' features a monochromatic finish on a suede upper accented with serrated three-stripes and a leather heel tab. The nylon tongue reveals foam padding for a throwback look, while perforated detailing on the quarter panel and toe box offers ventilated comfort. The blacked-out design up top is countered by a solid white rubber midsole.',
    'https://i.ebayimg.com/images/g/HdAAAOSwzcdftYkA/s-l500.jpg',
    150,
    169,
    3451
), (
    'adidas Torsion TRDC Bliss',
    'Adidas',
    'Core White/Bliss/Core Black',
    'Torsion TRDC',
    '2020',
    '2020-06-01',
    130,
    62,
    'Blending summertime tones with bright, sporty accents and a rugged build, the “Bliss” is a modern-day urban trekker that''s also up for a weekend hike. The top half serves up a compellingly cacophonous construction, using meshes, suedes, leathers and synthetics on its multitude of panels and twisting overlays. Toeboxes are mainly white and tan, with the midfoot adding black and yellow into the mix and heels bringing everything together. Small punches of blue appear on the anchored fabric Three Stripes graphic, collar and throat, the last of which is made from a textured neoprene.',
    'https://i.ebayimg.com/images/g/AtYAAOSw~Jhf8q9T/s-l1600.jpg',
    88,
    94,
    1232
), (
    'Nike Go FlyEase Black',
    'Nike',
    'Black/Anthracite/Racer Blue',
    'Go FlyEase',
    '2021',
    '2021-02-15',
    120,
    72,
    'The Nike Go FlyEase ''Black'' represents one of three introductory colorways of the brand''s revolutionary hands-free sneaker. The unique technology that underpins the shoe''s accessibility is the patent-pending bi-stable hinge, secured with a rubber midsole tensioner that extends from the toe and wraps around the back of the heel. When the hinge is open, the back of the insole is raised in the air at a roughly 30-degree angle, allowing the foot to easily slip on and collapse the hinge. To take off the shoe, the wearer steps on the ''kickstand'' heel and simply steps out.',
    'https://assets.solesense.com/en/images/products/500/nike-go-flyease-black-cw5883-002_1.jpg',
    88,
    97,
    1268
), (
    'Nike Dunk Low Georgetown',
    'Nike',
    'Midnight Navy/grey/White',
    'Dunk',
    '2021',
    '2021-09-02',
    100,
    150,
    'The Nike Dunk Low ''Georgetown'' showcases a simplistic two-tone palette inspired by the Hoyas, arranged in archetypal color blocking that recalls the introductory ''Be True to Your School'' series from 1985. The leather upper is finished in a neutral grey base with contrasting overlays in a deep navy hue. Exterior branding hits include a woven Nike tongue tag and an embroidered Nike wordmark on the heel tab. The retro hoops shoe is mounted on a durable rubber cupsole, featuring crisp white sidewalls and a navy rubber outsole.',
    'https://cdn.shopify.com/s/files/1/0017/5908/4588/products/808965_01_jpg_750x.jpg',
    180,
    209,
    5342
), (
    'Nike Daybreak Undercover Black',
    'Nike',
    'Black/White',
    'Daybreak',
    '2019',
    '2019-06-07',
    160,
    100,
    'Japanese deconstructionist Jun Takahashi, via his Undercover label, reimagines the vintage Nike Daybreak silhouette with this June 2019 release. The Undercover x Daybreak &#39;Black&#39; features a white Swoosh on a black nylon upper with suede overlays framed at the heel by a molded TPU component. The midsole bears an UNDERCOVER - Jun Takahashi graphic surrounded by a paint splatter motif. The original 1979 Daybreak outsole stays true with a splayed tread pattern.',
    'https://ofour.com/wp-content/uploads/2019/06/Nike-Daybreak-Undercover-Black-4.jpg',
    140,
    170,
    2154
), (
    'Nike Canyon Medium Olive',
    'Nike',
    'Medium Olive/Cargo Khaki/White',
    'Canyon Sandal',
    '2020',
    '2020-04-01',
    75,
    64,
    'The Nike Canyon Sandal ''Cargo Khaki'' features a rugged ACG-inspired design, highlighted by a soft dual-density foam midsole and a rubber outsole with deep flex grooves and large lugs for superior traction. Up top, the textile upper is secured with adjustable triple-strap closure that delivers a personalized fit. Nike branding adorns the webbing pull tab atop the tongue, providing the open sandal with easy on and off.',
    'http://cdn.shopify.com/s/files/1/1182/3402/products/men_swatersports1.jpg?v=1653463918',
    70,
    80,
    4562
), (
    'Nike Zoom Rookie Black',
    'Nike',
    'Black/White-University Red',
    'Zoom Rookie',
    '2018',
    '2018-11-09',
    210,
    129,
    'The Nike Zoom Rookie ''Black'' sneaker was released in late 2018, seven years after the silhouette''s original release. The all-black colorway is slightly disrupted by a white Nike swoosh on the vamp and one cent logo on the tongue, and a University Red &#39;Flight&#39; script on the back pull tab. The sleek look of these high tops is inspired by different Penny Hardaway shoes he wore over the length of his career, including the Air Flight One, Air Go LWP, and also utilizing Nike''s Foamposite technology.',
    'https://cdn.fashdirect.com/webadmin/items/website/2397728/image_2_154982301833_1.jpg',
    140,
    160,
    2358
), (
    'Jordan Future Hyper Royal',
    'Jordan',
    'Hyper Royal/Hyper Royal-Phantom',
    'Air Jordan Future',
    '2018',
    '2018-07-01',
    150,
    65,
    'First introduced in 2011, the Nike Air Jordan Future sneaker combines elements of the AJ11 with a unique woven upper. The Air Jordan Future &#39;Hyper Royal&#39; sneaker was released July 2018 as an update to the innovative silhouette. The shoe sports a Hyper Royal colorway with a woven textile upper for a checkered effect. At the midfoot, a shank plate offers support, while foam and Air technology provide long-lasting comfort.',
    'https://i5.walmartimages.com/asr/a85a65d4-01e7-4b18-ac97-0257bb5fbf82_1.e7ed2e810b16738b7a043c40e8b21d0e.jpeg?odnHeight=612&odnWidth=612&odnBg=FFFFFF',
    80,
    95,
    1623
), (
    'Jordan B''Loyal PS ''White''',
    'Jordan',
    'White/Metallic Silver',
    'Jordan B''Loyal',
    '2020',
    '2020-11-29',
    75,
    75,
    'Fashioned for little kids, the Jordan B''Loyal PS ''White'' applies a pristine monochrome finish to a retro-inspired mid-top that takes its design cues from legacy Air Jordan models. The sneaker makes use of a white leather upper, fortified with a tonal patent leather overlay that wraps over the toe and across the midfoot. An open-hole tongue combines with a webbing pull tab at the heel to deliver easy on and off. Embroidered Jumpman branding decorates the perforated lateral ankle.',
    'https://cdn.shopify.com/s/files/1/0603/3031/1875/products/main-square_e37a1ff9-454a-407b-923c-b1e55146ad86.jpg?v=1656289736',
    80,
    82,
    4256
), (
    'Jordan Legacy 312 Flip',
    'Jordan',
    'White/White-Black',
    'Jordan Legacy 312',
    '2019',
    '2019-01-01',
    160,
    137,
    'A shout-out to Chicago''s 312 area code, the Jordan Legacy 312 ''Flip'' is inspired by the Air Jordan 1, Air Jordan 3 and the Alpha Force Low; the shoes Michael Jordan wore early in his career with the Chicago Bulls. Famed designer Don C. collaborated with Nike to design the revamped classic revealed to the shoe world in October 2018. With a grey and white debossed elephant print upper, this colorway is an homage to the Air Jordan 3 &#39;Flip&#39; colorway that released back in 2006.',
    'https://sneakers123.s3.amazonaws.com/release/345632/jordan-legacy-312-flip-at4040-100.jpg',
    150,
    184,
    3457
), (
    'Jordan Maxin 200 Camo',
    'Jordan',
    'Medium Olive/Black-Light Bone-Gym Red',
    'Jordan Maxin 200',
    '2020',
    '2020-05-28',
    130,
    96,
    'The Jordan Maxin 200 ''Camo'' features a retro-inspired design that blends details that call to mind legacy Jordan silhouettes. The upper combines glossy black patent leather with camo-print suede overlays and molded quarter-panel grills reminiscent of the Air Jordan 5. An Off-White foam midsole, housing a visible Max Air unit in the heel, rides on a herringbone traction outsole with translucent rubber in high-wear areas.',
    'https://www.thenextsole.com/storage/images/CD6107-200.png',
    103,
    134,
    4324
);

